// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Wms.ProductionLine.Infra.Data.Context;

namespace Wms.ProductionLine.Infra.Migrations
{
    [DbContext(typeof(ProductionLineContext))]
    [Migration("20190717185301_Add-ConfigurationHistory")]
    partial class AddConfigurationHistory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.History.ProductionLineConfigurationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int>("HistoryType");

                    b.Property<Guid>("ProductionLineConfigurationId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineConfigurationId");

                    b.ToTable("ProductionLineConfigurationHistory");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.ProductionLineConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.ToTable("ProductionLineConfiguration");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.History.ProductionLineConfigurationHistory", b =>
                {
                    b.HasOne("Wms.ProductionLine.Domain.Entities.ProductionLineConfiguration", "ProductionLineConfiguration")
                        .WithMany("History")
                        .HasForeignKey("ProductionLineConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
