// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Wms.ProductionLine.Infra.Data.Context;

namespace Wms.ProductionLine.Infra.Migrations
{
    [DbContext(typeof(ProductionLineContext))]
    [ExcludeFromCodeCoverage]
    partial class ProductionLineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<bool>("Enabled");

                    b.Property<int>("Sequence");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.History.ProductionLineConfigurationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description");

                    b.Property<int>("HistoryType");

                    b.Property<Guid>("ProductionLineConfigurationId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProductionLineConfigurationId");

                    b.ToTable("ProductionLineConfigurationHistory");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.Integralizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<Guid>("ItemId");

                    b.Property<Guid?>("WarehouseId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Integralizado");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.IntegralizadoDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IntegralizadoId");

                    b.Property<Guid>("ItemId");

                    b.Property<double>("Quantity");

                    b.HasKey("Id");

                    b.HasIndex("IntegralizadoId");

                    b.HasIndex("ItemId");

                    b.ToTable("IntegralizadoDetail");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<int?>("ItemType");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.ProductionLineConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Enabled");

                    b.Property<Guid>("WarehouseId");

                    b.HasKey("Id");

                    b.ToTable("ProductionLineConfiguration");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<Guid?>("WarehouseId");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.History.ProductionLineConfigurationHistory", b =>
                {
                    b.HasOne("Wms.ProductionLine.Domain.Entities.ProductionLineConfiguration", "ProductionLineConfiguration")
                        .WithMany("History")
                        .HasForeignKey("ProductionLineConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.Integralizado", b =>
                {
                    b.HasOne("Wms.ProductionLine.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wms.ProductionLine.Domain.Entities.IntegralizadoDetail", b =>
                {
                    b.HasOne("Wms.ProductionLine.Domain.Entities.Integralizado", "Integralizado")
                        .WithMany("Details")
                        .HasForeignKey("IntegralizadoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wms.ProductionLine.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
